name: Upload Website
on:
  push:
    branches: 
    - master
env:
  AWS_REGION : us-east-1
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Sync S3
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: aws s3 sync ./public/ s3://$AWS_S3_BUCKET --follow-symlinks --delete

      - name: Invalidate CloudFront
        shell: bash
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*"
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "*"
          AWS_REGION:  ${{ env.AWS_REGION }}
